#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
server_dir=$(CDPATH= cd -- "$script_dir/.." && pwd)
ENV_FILE=${BALAUR_ENV_FILE:-"$server_dir/.env"}
cd "$server_dir"

TOTAL_STAGES=9

banner "Balaur Household Server setup"

stage "Household paths and address"
say "Set the versioned image, stable HTTPS address, data directory, and off-host backup destination."
ask BALAUR_HOUSEHOLD_IMAGE "Versioned Household Server image:"
ask BALAUR_PUBLIC_URL "Stable HTTPS address:"
ask BALAUR_DATA_DIR "PocketBase data directory:"
ask BALAUR_BACKUP_DESTINATION "Off-host backup directory:"
if [[ $BALAUR_PUBLIC_URL != https://* ]]; then
  warn "The public address must use HTTPS."
  exit 64
fi
write_env BALAUR_HOUSEHOLD_IMAGE "$BALAUR_HOUSEHOLD_IMAGE"
write_env BALAUR_PUBLIC_URL "${BALAUR_PUBLIC_URL%/}"
write_env BALAUR_DATA_DIR "$BALAUR_DATA_DIR"
write_env BALAUR_BACKUP_DESTINATION "$BALAUR_BACKUP_DESTINATION"
write_env BALAUR_PORT "8090"

stage "Google Cloud project"
say "Create or select the Google Cloud project that the Household controls."
open_url "https://console.cloud.google.com/projectcreate"
step "Create a project, or select the existing Household project."
pause "Continue after the correct project is active."
open_url "https://console.cloud.google.com/apis/library/calendar-json.googleapis.com"
step "Select Enable for the Google Calendar API."
pause "Continue after the API is enabled."

stage "Google OAuth audience"
say "Configure the private OAuth application and its allowed test accounts."
open_url "https://console.cloud.google.com/auth/branding"
step "Set the application name and Household support email."
open_url "https://console.cloud.google.com/auth/audience"
step "Use the Testing publishing status."
step "Add each Household Administrator who can connect Google Calendar."
pause "Continue after the test accounts are saved."

stage "Google OAuth client"
say "Create one web OAuth client for the Household Server callback."
open_url "https://console.cloud.google.com/auth/clients"
step "Select Create client, then select Web application."
step "Add this exact authorized redirect URI:"
say "${BALAUR_PUBLIC_URL%/}/api/balaur/calendar-source/callback"
step "Create the client, then copy its client identifier and secret."
ask BALAUR_GOOGLE_OAUTH_CLIENT_ID "Google OAuth client identifier:"
ask_secret BALAUR_GOOGLE_OAUTH_CLIENT_SECRET "Google OAuth client secret:"
write_env BALAUR_GOOGLE_OAUTH_CLIENT_ID "$BALAUR_GOOGLE_OAUTH_CLIENT_ID"
write_env BALAUR_GOOGLE_OAUTH_CLIENT_SECRET "$BALAUR_GOOGLE_OAUTH_CLIENT_SECRET"

stage "Calendar encryption key"
say "Create the unique AES-256-GCM key for this Household Server."
current_key=$(_existing BALAUR_CALENDAR_ENCRYPTION_KEY || true)
if [[ -n $current_key ]]; then
  BALAUR_CALENDAR_ENCRYPTION_KEY=$current_key
  note "The wizard kept the existing encryption key."
else
  BALAUR_CALENDAR_ENCRYPTION_KEY=$(openssl rand -base64 24)
fi
write_env BALAUR_CALENDAR_ENCRYPTION_KEY "$BALAUR_CALENDAR_ENCRYPTION_KEY"
chmod 600 "$ENV_FILE"

stage "DNS and HTTPS"
say "Point the Household domain to this host before Caddy requests a certificate."
step "Create the required A and AAAA records at your DNS provider."
step "Open server/Caddyfile.example and replace household.example.com."
step "Start Caddy with the example after DNS resolves."
pause "Continue after the HTTPS address opens without a certificate warning."

stage "Household Server deployment"
say "The wizard creates local directories and starts the versioned container."
confirm "Start the Household Server now?" || exit 0
mkdir -p "$BALAUR_DATA_DIR" "$BALAUR_BACKUP_DESTINATION"
docker compose up --build --detach
for _ in $(seq 1 60); do
  if curl --fail --silent --show-error "${BALAUR_PUBLIC_URL%/}/api/health" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done
curl --fail --silent --show-error "${BALAUR_PUBLIC_URL%/}/api/health" >/dev/null
say "The Household Server health check passed."

stage "First Household Administrator"
say "Open the one-time setup link from the Household Server logs."
docker compose logs --no-color household-server | tail -n 30
ask SETUP_URL "Paste the Household setup link:"
open_url "$SETUP_URL"
step "Enter the Household name, time zone, profile, email address, and password."
pause "Continue after the page reports that Household setup is complete."

stage "Backup and restore proof"
say "Create an off-host backup and prove that PocketBase can restore it."
confirm "Stop the server briefly for the backup and restore check?" || exit 0
docker compose stop
backup_path=$("$script_dir/backup.sh" "$BALAUR_DATA_DIR" "$BALAUR_BACKUP_DESTINATION")
docker compose up --detach
pocketbase=$("$script_dir/download-pocketbase.sh")
"$script_dir/verify-restore.sh" "$backup_path" "$pocketbase"
say "The backup and restore proof passed."

finish
