// GENERATED CODE - DO NOT MODIFY BY HAND

// dart format off
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_import, prefer_relative_imports, directives_ordering, unused_element, strict_raw_type
// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:widgetbook/widgetbook.dart' as _widgetbook;
import 'package:widgetbook_workspace/design_system/components/balaur_alert.stories.dart' as _widgetbook_workspace_design_system_components_balaur_alert_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_avatar.stories.dart' as _widgetbook_workspace_design_system_components_balaur_avatar_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_badge.stories.dart' as _widgetbook_workspace_design_system_components_balaur_badge_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_breadcrumb.stories.dart' as _widgetbook_workspace_design_system_components_balaur_breadcrumb_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_button.stories.dart' as _widgetbook_workspace_design_system_components_balaur_button_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_calendar_cell.stories.dart' as _widgetbook_workspace_design_system_components_balaur_calendar_cell_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_card.stories.dart' as _widgetbook_workspace_design_system_components_balaur_card_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_composer.stories.dart' as _widgetbook_workspace_design_system_components_balaur_composer_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_day_entry.stories.dart' as _widgetbook_workspace_design_system_components_balaur_day_entry_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_dialog_panel.stories.dart' as _widgetbook_workspace_design_system_components_balaur_dialog_panel_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_empty_state.stories.dart' as _widgetbook_workspace_design_system_components_balaur_empty_state_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_folk_band.stories.dart' as _widgetbook_workspace_design_system_components_balaur_folk_band_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_guardian_card.stories.dart' as _widgetbook_workspace_design_system_components_balaur_guardian_card_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_knowledge_card.stories.dart' as _widgetbook_workspace_design_system_components_balaur_knowledge_card_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_list.stories.dart' as _widgetbook_workspace_design_system_components_balaur_list_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_message_bubble.stories.dart' as _widgetbook_workspace_design_system_components_balaur_message_bubble_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_nudge_banner.stories.dart' as _widgetbook_workspace_design_system_components_balaur_nudge_banner_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_pagination.stories.dart' as _widgetbook_workspace_design_system_components_balaur_pagination_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_pips.stories.dart' as _widgetbook_workspace_design_system_components_balaur_pips_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_recap_card.stories.dart' as _widgetbook_workspace_design_system_components_balaur_recap_card_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_select.stories.dart' as _widgetbook_workspace_design_system_components_balaur_select_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_skeleton.stories.dart' as _widgetbook_workspace_design_system_components_balaur_skeleton_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_sparkline.stories.dart' as _widgetbook_workspace_design_system_components_balaur_sparkline_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_stat_card.stories.dart' as _widgetbook_workspace_design_system_components_balaur_stat_card_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_stitch.stories.dart' as _widgetbook_workspace_design_system_components_balaur_stitch_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_surface.stories.dart' as _widgetbook_workspace_design_system_components_balaur_surface_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_tabs.stories.dart' as _widgetbook_workspace_design_system_components_balaur_tabs_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_tag.stories.dart' as _widgetbook_workspace_design_system_components_balaur_tag_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_task_card.stories.dart' as _widgetbook_workspace_design_system_components_balaur_task_card_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_text_field.stories.dart' as _widgetbook_workspace_design_system_components_balaur_text_field_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_toast.stories.dart' as _widgetbook_workspace_design_system_components_balaur_toast_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_toggle.stories.dart' as _widgetbook_workspace_design_system_components_balaur_toggle_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_tool_row.stories.dart' as _widgetbook_workspace_design_system_components_balaur_tool_row_stories;
import 'package:widgetbook_workspace/design_system/components/balaur_topbar.stories.dart' as _widgetbook_workspace_design_system_components_balaur_topbar_stories;
import 'package:widgetbook_workspace/household/presentation/household_account_screen.stories.dart' as _widgetbook_workspace_household_presentation_household_account_screen_stories;
import 'package:widgetbook_workspace/household/presentation/household_invitations_screen.stories.dart' as _widgetbook_workspace_household_presentation_household_invitations_screen_stories;
import 'package:widgetbook_workspace/household/presentation/household_pairing_gate.stories.dart' as _widgetbook_workspace_household_presentation_household_pairing_gate_stories;
import 'package:widgetbook_workspace/household/presentation/household_pairing_view.stories.dart' as _widgetbook_workspace_household_presentation_household_pairing_view_stories;
import 'package:widgetbook_workspace/household/presentation/household_qr_scanner_screen.stories.dart' as _widgetbook_workspace_household_presentation_household_qr_scanner_screen_stories;
import 'package:widgetbook_workspace/navigation/presentation/balaur_navigation_shell.stories.dart' as _widgetbook_workspace_navigation_presentation_balaur_navigation_shell_stories;
import 'package:widgetbook_workspace/screens/balaur_reference_screen.stories.dart' as _widgetbook_workspace_screens_balaur_reference_screen_stories;
import 'package:widgetbook_workspace/settings/presentation/provider_settings_screen.stories.dart' as _widgetbook_workspace_settings_presentation_provider_settings_screen_stories;

final components = <_widgetbook.Component>[
  _widgetbook_workspace_design_system_components_balaur_alert_stories.BalaurAlertComponent,
  _widgetbook_workspace_design_system_components_balaur_avatar_stories.BalaurAvatarComponent,
  _widgetbook_workspace_design_system_components_balaur_badge_stories.BalaurBadgeComponent,
  _widgetbook_workspace_design_system_components_balaur_breadcrumb_stories.BalaurBreadcrumbComponent,
  _widgetbook_workspace_design_system_components_balaur_button_stories.BalaurButtonComponent,
  _widgetbook_workspace_design_system_components_balaur_calendar_cell_stories.BalaurCalendarCellComponent,
  _widgetbook_workspace_design_system_components_balaur_card_stories.BalaurCardComponent,
  _widgetbook_workspace_design_system_components_balaur_composer_stories.BalaurComposerComponent,
  _widgetbook_workspace_design_system_components_balaur_day_entry_stories.BalaurDayEntryComponent,
  _widgetbook_workspace_design_system_components_balaur_dialog_panel_stories.BalaurDialogPanelComponent,
  _widgetbook_workspace_design_system_components_balaur_empty_state_stories.BalaurEmptyStateComponent,
  _widgetbook_workspace_design_system_components_balaur_folk_band_stories.BalaurFolkBandComponent,
  _widgetbook_workspace_design_system_components_balaur_guardian_card_stories.BalaurGuardianCardComponent,
  _widgetbook_workspace_design_system_components_balaur_knowledge_card_stories.BalaurKnowledgeCardComponent,
  _widgetbook_workspace_design_system_components_balaur_list_stories.BalaurListComponent,
  _widgetbook_workspace_design_system_components_balaur_message_bubble_stories.BalaurMessageBubbleComponent,
  _widgetbook_workspace_design_system_components_balaur_nudge_banner_stories.BalaurNudgeBannerComponent,
  _widgetbook_workspace_design_system_components_balaur_pagination_stories.BalaurPaginationComponent,
  _widgetbook_workspace_design_system_components_balaur_pips_stories.BalaurPipsComponent,
  _widgetbook_workspace_design_system_components_balaur_recap_card_stories.BalaurRecapCardComponent,
  _widgetbook_workspace_design_system_components_balaur_select_stories.BalaurSelectComponent,
  _widgetbook_workspace_design_system_components_balaur_skeleton_stories.BalaurSkeletonComponent,
  _widgetbook_workspace_design_system_components_balaur_sparkline_stories.BalaurSparklineComponent,
  _widgetbook_workspace_design_system_components_balaur_stat_card_stories.BalaurStatCardComponent,
  _widgetbook_workspace_design_system_components_balaur_stitch_stories.BalaurStitchComponent,
  _widgetbook_workspace_design_system_components_balaur_surface_stories.BalaurSurfaceComponent,
  _widgetbook_workspace_design_system_components_balaur_tabs_stories.BalaurTabsComponent,
  _widgetbook_workspace_design_system_components_balaur_tag_stories.BalaurTagComponent,
  _widgetbook_workspace_design_system_components_balaur_task_card_stories.BalaurTaskCardComponent,
  _widgetbook_workspace_design_system_components_balaur_text_field_stories.BalaurTextFieldComponent,
  _widgetbook_workspace_design_system_components_balaur_toast_stories.BalaurToastComponent,
  _widgetbook_workspace_design_system_components_balaur_toggle_stories.BalaurToggleComponent,
  _widgetbook_workspace_design_system_components_balaur_tool_row_stories.BalaurToolRowComponent,
  _widgetbook_workspace_design_system_components_balaur_topbar_stories.BalaurTopbarComponent,
  _widgetbook_workspace_household_presentation_household_account_screen_stories.HouseholdAccountScreenComponent,
  _widgetbook_workspace_household_presentation_household_invitations_screen_stories.HouseholdInvitationsScreenComponent,
  _widgetbook_workspace_household_presentation_household_pairing_gate_stories.HouseholdPairingGateComponent,
  _widgetbook_workspace_household_presentation_household_pairing_view_stories.HouseholdPairingViewComponent,
  _widgetbook_workspace_household_presentation_household_qr_scanner_screen_stories.HouseholdQrScannerScreenComponent,
  _widgetbook_workspace_navigation_presentation_balaur_navigation_shell_stories.BalaurNavigationShellComponent,
  _widgetbook_workspace_screens_balaur_reference_screen_stories.BalaurReferenceScreenComponent,
  _widgetbook_workspace_settings_presentation_provider_settings_screen_stories.ProviderSettingsScreenComponent,
];
